<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'xavi_shop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'MuVynYAfHNWXgyinm8HbT7NFoB9DNO3Uy06DTy0nS9sVjZXRSGkeZW8e');
define('_COOKIE_IV_', 'kVHXLfPX');
define('_PS_CREATION_DATE_', '2014-09-17');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '0tk20EJAvTVj4eT1MrABBbIubhXHP2z9');
define('_RIJNDAEL_IV_', 'QT6xM8WMn/lFJPSAjZAHfA==');
